name: Build extras
on: [push]
jobs:
  build:
    name: Build on ${{matrix.container }}
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container: [ 'ubuntu:18.04' ]
    steps:
      - uses: actions/checkout@v1.0.0
      - name: build packages
        run: cd extras; bash build.sh ${{ matrix.container }}