name: Docker Image CI amd64

on:
  schedule:
    - cron: "30 1 * * *"
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Run Buildx
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} \
                       -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --no-cache \
            --file Dockerfile -t icnteam/vhost:22.02 \
            --push .
